### PR TITLE
Add timeout to MapBuilder, store process time

### PR DESCRIPTION
**Pull request by mkhorton**
So we can modify the BVBuilder to set a max time.

Disabled by default.

### CODE REVIEW

**Comment by dwinston** [comment]
Could we have `Timeout.seconds` default to `None` instead of `16 * 24 * 60 * 60 / 1e5 == 13.824` seconds? So that a user has to enter the value? We can include "assuming a maximum running time of 1 day for 100,000 items parallelized across 16 cores, you would set this to `16 * 24 * 60 * 60 / 1e5`" as an aid to a user.

**Comment by mkhorton** [comment]
It does default to None in the MapBuilder. If you’re importing Timeout manually you presumably want some kind of non-zero timeout.

**Comment by dwinston** [comment]
Okay, then can the number `13.824` be put somewhere in the docstring to spare any manual importer from having to evaluate that expression?

**Comment by mkhorton** [comment]
Done

**Pull request merged**
