### PR TITLE
Add GridFSURIStore with support for URI connections

### PR DESCRIPTION
**Pull request by utf**
There's already a version of MongoStore that supports URI connection strings. This PR adds the equivalent for GridFSStore. The only difference between the stores is the connection method and init parameters.

There is already an issue suggesting to merge MongoStore and MongoURIStore which would make this PR obselete (#483) but I will leave that for future work.

If this looks ok, once merged please can you push a new version.

### CODE REVIEW

**Comment by utf** [comment]
The failing tests are unrelated to this PR. E.g., same tests fail in  #503

**Comment by munrojm** [comment]
Do you mind if I try and fix the tests in this branch before I merge @utf?

**Comment by utf** [comment]
No, go for it!

**Comment by munrojm** [comment]
Actually, will merge now and fix in another branch.

**Comment by munrojm** [comment]
@utf new release is out with your additions.

**Comment by utf** [comment]
Thanks!

**Pull request merged**
