### PR TITLE
[WIP] Add EndpointCluster and ClusterManager to maggma

### PR DESCRIPTION
**Pull request by wuxiaohua1011**
This pull request is a WIP for the implementation of EndpointCluster and ClusterManager. The general idea to is build a simple API framework for dissemenation that is configuration based where possible. Critical goals for this framework are:
- easy to test
- modularized
- and have a pipelined data flow across endpoints(but at the same time, each app is modularized)

To accomplish this, we're building two core classes: one to create an endpoint and one to organize them.

### The API Endpoint

- [x] Generic core interface that can be implemented to enable get/put/post/patch/delete operations
- [x] A simple read-only endpoint: `GET` on `/` and `GET` with query params on `GET`
- [x] Add pagination query params
- [x] Add default fields to Endpoint and query param for projected fields
- [x] Add `all` option to projected fields
- [x] Add `aliased_fields` to rename fields from document to response
- [x] Add interface to build query operators on the fly for fields
- [x] Add `not_eq` operator
- [x] Add `lt` , `gt` then operators
- [x] Add `in` , and `not_in` operators

#### Endpoint Manager

- [x] Load endpoints dynamically
- [x] Organize endpoints for complex API
- [ ] Run endpoints in python as a testable implementation
- [ ] Add feature to `mrun` to run the manager + endpoints in a production environment

### CODE REVIEW

**Comment by shyamd** [comment]
Next step is to clean up empty files and duplicates. It looks like the root definitin of cluster manager and endpoint cluster are missing from `maggma.core`

**Comment by wuxiaohua1011** [comment]
This is a E203 error by Flake8
[Flake8 Error](https://drive.google.com/file/d/10LKSxHYarx2yHW2KgW0riRBLsBfhdPxO/view?usp=sharing)

[Black Error](https://drive.google.com/file/d/1fxR0msej--8335gzX1vxuUBrz2zNEFNt/view?usp=sharing)

**Comment by wuxiaohua1011** [comment]
Next is to build the part for actually querying database.

**Comment by wuxiaohua1011** [comment]
woops, alias got deleted somehow through the process... i will reimplement it, not hard, just a dictionary mapping thing

**Pull request merged**
