### PR TITLE
JSONStore: file_writable -> read_only

### PR DESCRIPTION
**Pull request by rkingsbury**
This PR adds a `read_only` kwarg to `JSONStore` to replace `file_writable`.

## Contributor Checklist

- [x] I have broken down my PR scope into the following TODO tasks
   -  [x] add read_only
   - [x] add backwards compatibility logic to continue supporting file_writable
- [x] I have run the tests locally and they passed.
- [x] I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR

### CODE REVIEW

**Comment by rkingsbury** [comment]
> I think we should maybe only keep `read_only` as an explicit argument that is passed. We can then absorb any mention of `file_writable` into `**kwargs`. Do you have an opinion on that?

Just to make sure I understand what you're saying, do you mean, e.g. 

```
class JSONStore(MemoryStore):
    """
    A Store for access to a single or multiple JSON files
    """

    def __init__(
        self,
        paths: Union[str, List[str]],
        read_only: bool,
        file_writable: Optional[bool] = None,
        **kwargs,
    ):
```

in other words, the user always has to specify `read_only` ?

**Comment by munrojm** [comment]
Yeah, exactly.

**Comment by rkingsbury** [comment]
OK, will this cause compatibility problems though? Because if we're trying to support legacy code that says, e.g. `js=JSONStore(<filename>)` that would start to fail since it doesn't specify `read_only`.

**Comment by munrojm** [comment]
Oh, sorry for not being clear. It can be optional, I just wanted to suggest changing how `file_writable` is handled so it isn't explicitly in the function signature anymore.

**Pull request merged**
