### PR TITLE
Add read_only flag to Stores, set to read_only by default for source Stores

### PR DESCRIPTION
**Pull request by mkhorton**
@dwinston mentioned this previously, thought it might be useful to enforce good builder hygiene

### CODE REVIEW

**Comment by dwinston** [comment]
Great, thanks! Please add a test for this, i.e. assertRaises, and I'll merge.

**Comment by dwinston** [comment]
Sorry, I wasn't clear about the test. I'd like a test that runs a simple builder that tries to write to a source store.

**Comment by mkhorton** [comment]
Np, but I'm not familiar enough with MagicMock to write a builder test, will have to take a look at it another day

**Comment by shyamd** [comment]
I'm closing this for now since this can be achieved with appropriate credentials which are a safer way to ensure ReadOnly and ReadWrite.

**Pull request closed without merging**
